/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.enums;

/**
 * This class is generated by jOOQ.
 *
 * simple, fast
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TestprofileMode implements org.jooq.EnumType {

	NORMAL("NORMAL"),

	FAST("FAST"),

	;

	private final java.lang.String literal;

	private TestprofileMode(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Schema getSchema() {
		return null;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "testprofile_mode";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
