/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceType extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.DeviceTypeRecord> {

	private static final long serialVersionUID = 889857812;

	/**
	 * The singleton instance of <code>cbt.device_type</code>
	 */
	public static final com.cbt.ws.jooq.tables.DeviceType DEVICE_TYPE = new com.cbt.ws.jooq.tables.DeviceType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.DeviceTypeRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.DeviceTypeRecord.class;
	}

	/**
	 * The column <code>cbt.device_type.id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceTypeRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device_type.model</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceTypeRecord, java.lang.String> MODEL = createField("model", org.jooq.impl.SQLDataType.CHAR.length(100), this);

	/**
	 * The column <code>cbt.device_type.manufacture</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceTypeRecord, java.lang.String> MANUFACTURE = createField("manufacture", org.jooq.impl.SQLDataType.CHAR.length(100), this);

	/**
	 * The column <code>cbt.device_type.updated</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceTypeRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>cbt.device_type</code> table reference
	 */
	public DeviceType() {
		super("device_type", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.device_type</code> table reference
	 */
	public DeviceType(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.DeviceTypeRecord, java.lang.Long> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_DEVICE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceTypeRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_DEVICE_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceTypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceTypeRecord>>asList(com.cbt.ws.jooq.Keys.KEY_DEVICE_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.DeviceType as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.DeviceType(alias);
	}
}
