/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Device extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.DeviceRecord> {

	private static final long serialVersionUID = -481581526;

	/**
	 * The singleton instance of <code>cbt.device</code>
	 */
	public static final com.cbt.ws.jooq.tables.Device DEVICE = new com.cbt.ws.jooq.tables.Device();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.DeviceRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.DeviceRecord.class;
	}

	/**
	 * The column <code>cbt.device.id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device.serial_number</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.String> SERIAL_NUMBER = createField("serial_number", org.jooq.impl.SQLDataType.CHAR.length(255), this);

	/**
	 * The column <code>cbt.device.owner_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.Long> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device.device_unique_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.String> DEVICE_UNIQUE_ID = createField("device_unique_id", org.jooq.impl.SQLDataType.CHAR.length(255), this);

	/**
	 * The column <code>cbt.device.device_type_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.Long> DEVICE_TYPE_ID = createField("device_type_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device.state</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, com.cbt.ws.jooq.enums.DeviceState> STATE = createField("state", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.cbt.ws.jooq.enums.DeviceState.class), this);

	/**
	 * The column <code>cbt.device.device_os_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.Long> DEVICE_OS_ID = createField("device_os_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device.updated</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>cbt.device</code> table reference
	 */
	public Device() {
		super("device", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.device</code> table reference
	 */
	public Device(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.Device.DEVICE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.DeviceRecord, java.lang.Long> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_DEVICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_DEVICE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceRecord>>asList(com.cbt.ws.jooq.Keys.KEY_DEVICE_PRIMARY, com.cbt.ws.jooq.Keys.KEY_DEVICE_DEVICEUNIQUE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.Device as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.Device(alias);
	}
}
