/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceOs extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.DeviceOsRecord> {

	private static final long serialVersionUID = -903849175;

	/**
	 * The singleton instance of <code>cbt.device_os</code>
	 */
	public static final com.cbt.ws.jooq.tables.DeviceOs DEVICE_OS = new com.cbt.ws.jooq.tables.DeviceOs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.DeviceOsRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.DeviceOsRecord.class;
	}

	/**
	 * The column <code>cbt.device_os.deviceos_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceOsRecord, java.lang.Long> DEVICEOS_ID = createField("deviceos_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device_os.name</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceOsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(255), this);

	/**
	 * Create a <code>cbt.device_os</code> table reference
	 */
	public DeviceOs() {
		super("device_os", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.device_os</code> table reference
	 */
	public DeviceOs(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.DeviceOs.DEVICE_OS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.DeviceOsRecord, java.lang.Long> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_DEVICE_OS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceOsRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_DEVICE_OS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceOsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceOsRecord>>asList(com.cbt.ws.jooq.Keys.KEY_DEVICE_OS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.DeviceOs as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.DeviceOs(alias);
	}
}
