/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceSharing extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.DeviceSharingRecord> {

	private static final long serialVersionUID = 70789542;

	/**
	 * The singleton instance of <code>cbt.device_sharing</code>
	 */
	public static final com.cbt.ws.jooq.tables.DeviceSharing DEVICE_SHARING = new com.cbt.ws.jooq.tables.DeviceSharing();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.DeviceSharingRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.DeviceSharingRecord.class;
	}

	/**
	 * The column <code>cbt.device_sharing.device_sharing_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceSharingRecord, java.lang.Long> DEVICE_SHARING_ID = createField("device_sharing_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device_sharing.device_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceSharingRecord, java.lang.Long> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.device_sharing.user_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.DeviceSharingRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>cbt.device_sharing</code> table reference
	 */
	public DeviceSharing() {
		super("device_sharing", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.device_sharing</code> table reference
	 */
	public DeviceSharing(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.DeviceSharingRecord, java.lang.Long> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_DEVICE_SHARING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceSharingRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_DEVICE_SHARING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceSharingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.DeviceSharingRecord>>asList(com.cbt.ws.jooq.Keys.KEY_DEVICE_SHARING_PRIMARY, com.cbt.ws.jooq.Keys.KEY_DEVICE_SHARING_DEVICE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.DeviceSharing as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.DeviceSharing(alias);
	}
}
