/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestprofileDevices extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord> {

	private static final long serialVersionUID = 973812814;

	/**
	 * The singleton instance of <code>cbt.testprofile_devices</code>
	 */
	public static final com.cbt.ws.jooq.tables.TestprofileDevices TESTPROFILE_DEVICES = new com.cbt.ws.jooq.tables.TestprofileDevices();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord.class;
	}

	/**
	 * The column <code>cbt.testprofile_devices.id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>cbt.testprofile_devices.testprofile_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord, java.lang.Long> TESTPROFILE_ID = createField("testprofile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.testprofile_devices.devicetype_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord, java.lang.Long> DEVICETYPE_ID = createField("devicetype_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>cbt.testprofile_devices</code> table reference
	 */
	public TestprofileDevices() {
		super("testprofile_devices", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.testprofile_devices</code> table reference
	 */
	public TestprofileDevices(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.TestprofileDevices.TESTPROFILE_DEVICES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord, java.lang.Integer> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_TESTPROFILE_DEVICES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_TESTPROFILE_DEVICES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.TestprofileDevicesRecord>>asList(com.cbt.ws.jooq.Keys.KEY_TESTPROFILE_DEVICES_PRIMARY, com.cbt.ws.jooq.Keys.KEY_TESTPROFILE_DEVICES_TESTPROFILE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.TestprofileDevices as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.TestprofileDevices(alias);
	}
}
