/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testtarget extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.TesttargetRecord> {

	private static final long serialVersionUID = -1128705617;

	/**
	 * The singleton instance of <code>cbt.testtarget</code>
	 */
	public static final com.cbt.ws.jooq.tables.Testtarget TESTTARGET = new com.cbt.ws.jooq.tables.Testtarget();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.TesttargetRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.TesttargetRecord.class;
	}

	/**
	 * The column <code>cbt.testtarget.id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.testtarget.name</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cbt.testtarget.user_id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.testtarget.path</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.String> PATH = createField("path", org.jooq.impl.SQLDataType.CHAR.length(255), this);

	/**
	 * The column <code>cbt.testtarget.file_name</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.CHAR.length(255), this);

	/**
	 * The column <code>cbt.testtarget.updated</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cbt.testtarget.metadata</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.String> METADATA = createField("metadata", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * Create a <code>cbt.testtarget</code> table reference
	 */
	public Testtarget() {
		super("testtarget", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.testtarget</code> table reference
	 */
	public Testtarget(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.Testtarget.TESTTARGET);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.TesttargetRecord, java.lang.Long> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_TESTTARGET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.TesttargetRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_TESTTARGET_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.TesttargetRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.TesttargetRecord>>asList(com.cbt.ws.jooq.Keys.KEY_TESTTARGET_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.Testtarget as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.Testtarget(alias);
	}
}
