/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.cbt.ws.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = -69560747;

	/**
	 * The singleton instance of <code>cbt.user</code>
	 */
	public static final com.cbt.ws.jooq.tables.User USER = new com.cbt.ws.jooq.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cbt.ws.jooq.tables.records.UserRecord> getRecordType() {
		return com.cbt.ws.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>cbt.user.id</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.UserRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cbt.user.name</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.UserRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(30), this);

	/**
	 * The column <code>cbt.user.password</code>. 
	 */
	public final org.jooq.TableField<com.cbt.ws.jooq.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CHAR.length(255), this);

	/**
	 * Create a <code>cbt.user</code> table reference
	 */
	public User() {
		super("user", com.cbt.ws.jooq.Cbt.CBT);
	}

	/**
	 * Create an aliased <code>cbt.user</code> table reference
	 */
	public User(java.lang.String alias) {
		super(alias, com.cbt.ws.jooq.Cbt.CBT, com.cbt.ws.jooq.tables.User.USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.cbt.ws.jooq.tables.records.UserRecord, java.lang.Long> getIdentity() {
		return com.cbt.ws.jooq.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.UserRecord> getPrimaryKey() {
		return com.cbt.ws.jooq.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cbt.ws.jooq.tables.records.UserRecord>>asList(com.cbt.ws.jooq.Keys.KEY_USER_PRIMARY, com.cbt.ws.jooq.Keys.KEY_USER_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.tables.User as(java.lang.String alias) {
		return new com.cbt.ws.jooq.tables.User(alias);
	}
}
