/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.DeviceRecord> implements org.jooq.Record8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, com.cbt.ws.jooq.enums.DeviceState, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = -1650894371;

	/**
	 * Setter for <code>cbt.device.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.device.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.device.serial_number</code>. 
	 */
	public void setSerialNumber(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.device.serial_number</code>. 
	 */
	public java.lang.String getSerialNumber() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cbt.device.owner_id</code>. 
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.device.owner_id</code>. 
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>cbt.device.device_unique_id</code>. 
	 */
	public void setDeviceUniqueId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbt.device.device_unique_id</code>. 
	 */
	public java.lang.String getDeviceUniqueId() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>cbt.device.device_type_id</code>. 
	 */
	public void setDeviceTypeId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbt.device.device_type_id</code>. 
	 */
	public java.lang.Long getDeviceTypeId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>cbt.device.state</code>. 
	 */
	public void setState(com.cbt.ws.jooq.enums.DeviceState value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbt.device.state</code>. 
	 */
	public com.cbt.ws.jooq.enums.DeviceState getState() {
		return (com.cbt.ws.jooq.enums.DeviceState) getValue(5);
	}

	/**
	 * Setter for <code>cbt.device.device_os_id</code>. 
	 */
	public void setDeviceOsId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cbt.device.device_os_id</code>. 
	 */
	public java.lang.Long getDeviceOsId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>cbt.device.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cbt.device.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, com.cbt.ws.jooq.enums.DeviceState, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, com.cbt.ws.jooq.enums.DeviceState, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.SERIAL_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.DEVICE_UNIQUE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.DEVICE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.cbt.ws.jooq.enums.DeviceState> field6() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.DEVICE_OS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.cbt.ws.jooq.tables.Device.DEVICE.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSerialNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDeviceUniqueId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getDeviceTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.enums.DeviceState value6() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getDeviceOsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getUpdated();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DeviceRecord
	 */
	public DeviceRecord() {
		super(com.cbt.ws.jooq.tables.Device.DEVICE);
	}
}
