/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceTypeRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.DeviceTypeRecord> implements org.jooq.Record4<java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -203281874;

	/**
	 * Setter for <code>cbt.device_type.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.device_type.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.device_type.model</code>. 
	 */
	public void setModel(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.device_type.model</code>. 
	 */
	public java.lang.String getModel() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cbt.device_type.manufacture</code>. 
	 */
	public void setManufacture(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.device_type.manufacture</code>. 
	 */
	public java.lang.String getManufacture() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cbt.device_type.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbt.device_type.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE.MANUFACTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getManufacture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getUpdated();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DeviceTypeRecord
	 */
	public DeviceTypeRecord() {
		super(com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE);
	}
}
