/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceSharingRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.DeviceSharingRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -935753239;

	/**
	 * Setter for <code>cbt.device_sharing.device_sharing_id</code>. 
	 */
	public void setDeviceSharingId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.device_sharing.device_sharing_id</code>. 
	 */
	public java.lang.Long getDeviceSharingId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.device_sharing.device_id</code>. 
	 */
	public void setDeviceId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.device_sharing.device_id</code>. 
	 */
	public java.lang.Long getDeviceId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cbt.device_sharing.user_id</code>. 
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.device_sharing.user_id</code>. 
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING.DEVICE_SHARING_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getDeviceSharingId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DeviceSharingRecord
	 */
	public DeviceSharingRecord() {
		super(com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING);
	}
}
