/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResultsRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.ResultsRecord> implements org.jooq.Record4<java.lang.Long, com.cbt.ws.jooq.enums.ResultsState, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 1369793029;

	/**
	 * Setter for <code>cbt.results.result_id</code>. 
	 */
	public void setResultId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.results.result_id</code>. 
	 */
	public java.lang.Long getResultId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.results.state</code>. 
	 */
	public void setState(com.cbt.ws.jooq.enums.ResultsState value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.results.state</code>. 
	 */
	public com.cbt.ws.jooq.enums.ResultsState getState() {
		return (com.cbt.ws.jooq.enums.ResultsState) getValue(1);
	}

	/**
	 * Setter for <code>cbt.results.metadata</code>. json string of metadata values
	 */
	public void setMetadata(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.results.metadata</code>. json string of metadata values
	 */
	public java.lang.String getMetadata() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cbt.results.test_id</code>. 
	 */
	public void setTestId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbt.results.test_id</code>. 
	 */
	public java.lang.Long getTestId() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, com.cbt.ws.jooq.enums.ResultsState, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, com.cbt.ws.jooq.enums.ResultsState, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.Results.RESULTS.RESULT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.cbt.ws.jooq.enums.ResultsState> field2() {
		return com.cbt.ws.jooq.tables.Results.RESULTS.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.cbt.ws.jooq.tables.Results.RESULTS.METADATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.cbt.ws.jooq.tables.Results.RESULTS.TEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getResultId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.enums.ResultsState value2() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getMetadata();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getTestId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ResultsRecord
	 */
	public ResultsRecord() {
		super(com.cbt.ws.jooq.tables.Results.RESULTS);
	}
}
