/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestconfigRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.TestconfigRecord> implements org.jooq.Record8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = 586927848;

	/**
	 * Setter for <code>cbt.testconfig.test_config_id</code>. 
	 */
	public void setTestConfigId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.test_config_id</code>. 
	 */
	public java.lang.Long getTestConfigId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.testconfig.test_config_name</code>. 
	 */
	public void setTestConfigName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.test_config_name</code>. 
	 */
	public java.lang.String getTestConfigName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cbt.testconfig.user_id</code>. 
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.user_id</code>. 
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>cbt.testconfig.test_script_id</code>. 
	 */
	public void setTestScriptId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.test_script_id</code>. 
	 */
	public java.lang.Long getTestScriptId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>cbt.testconfig.test_target_id</code>. 
	 */
	public void setTestTargetId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.test_target_id</code>. 
	 */
	public java.lang.Long getTestTargetId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>cbt.testconfig.test_profile_id</code>. 
	 */
	public void setTestProfileId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.test_profile_id</code>. 
	 */
	public java.lang.Long getTestProfileId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>cbt.testconfig.metadata</code>. 
	 */
	public void setMetadata(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.metadata</code>. 
	 */
	public java.lang.String getMetadata() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>cbt.testconfig.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cbt.testconfig.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.TEST_CONFIG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.TEST_CONFIG_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.TEST_SCRIPT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.TEST_TARGET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.TEST_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.METADATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getTestConfigId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTestConfigName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getTestScriptId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getTestTargetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getTestProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getMetadata();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getUpdated();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestconfigRecord
	 */
	public TestconfigRecord() {
		super(com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG);
	}
}
