/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestprofileRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.TestprofileRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Long, java.lang.String, com.cbt.ws.jooq.enums.TestprofileMode, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = -1607092680;

	/**
	 * Setter for <code>cbt.testprofile.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.testprofile.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.testprofile.user_id</code>. 
	 */
	public void setUserId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.testprofile.user_id</code>. 
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cbt.testprofile.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.testprofile.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cbt.testprofile.mode</code>. simple, fast
	 */
	public void setMode(com.cbt.ws.jooq.enums.TestprofileMode value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbt.testprofile.mode</code>. simple, fast
	 */
	public com.cbt.ws.jooq.enums.TestprofileMode getMode() {
		return (com.cbt.ws.jooq.enums.TestprofileMode) getValue(3);
	}

	/**
	 * Setter for <code>cbt.testprofile.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbt.testprofile.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>cbt.testprofile.metadata</code>. 
	 */
	public void setMetadata(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbt.testprofile.metadata</code>. 
	 */
	public java.lang.String getMetadata() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, com.cbt.ws.jooq.enums.TestprofileMode, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, com.cbt.ws.jooq.enums.TestprofileMode, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.cbt.ws.jooq.enums.TestprofileMode> field4() {
		return com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE.MODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE.METADATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.enums.TestprofileMode value4() {
		return getMode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMetadata();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestprofileRecord
	 */
	public TestprofileRecord() {
		super(com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE);
	}
}
