/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestrunRecord extends org.jooq.impl.UpdatableRecordImpl<com.cbt.ws.jooq.tables.records.TestrunRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, com.cbt.ws.jooq.enums.TestrunStatus> {

	private static final long serialVersionUID = -2126790668;

	/**
	 * Setter for <code>cbt.testrun.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbt.testrun.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cbt.testrun.user_id</code>. 
	 */
	public void setUserId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbt.testrun.user_id</code>. 
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cbt.testrun.test_config_id</code>. 
	 */
	public void setTestConfigId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbt.testrun.test_config_id</code>. 
	 */
	public java.lang.Long getTestConfigId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>cbt.testrun.created</code>. 
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbt.testrun.created</code>. 
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>cbt.testrun.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbt.testrun.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>cbt.testrun.status</code>. 
	 */
	public void setStatus(com.cbt.ws.jooq.enums.TestrunStatus value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbt.testrun.status</code>. 
	 */
	public com.cbt.ws.jooq.enums.TestrunStatus getStatus() {
		return (com.cbt.ws.jooq.enums.TestrunStatus) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, com.cbt.ws.jooq.enums.TestrunStatus> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, com.cbt.ws.jooq.enums.TestrunStatus> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.cbt.ws.jooq.tables.Testrun.TESTRUN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.cbt.ws.jooq.tables.Testrun.TESTRUN.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.cbt.ws.jooq.tables.Testrun.TESTRUN.TEST_CONFIG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.cbt.ws.jooq.tables.Testrun.TESTRUN.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.cbt.ws.jooq.tables.Testrun.TESTRUN.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.cbt.ws.jooq.enums.TestrunStatus> field6() {
		return com.cbt.ws.jooq.tables.Testrun.TESTRUN.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getTestConfigId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.cbt.ws.jooq.enums.TestrunStatus value6() {
		return getStatus();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestrunRecord
	 */
	public TestrunRecord() {
		super(com.cbt.ws.jooq.tables.Testrun.TESTRUN);
	}
}
