/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cbt extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1729388515;

	/**
	 * The singleton instance of <code>cbt</code>
	 */
	public static final Cbt CBT = new Cbt();

	/**
	 * No further instances allowed
	 */
	private Cbt() {
		super("cbt");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.cbt.ws.jooq.tables.Device.DEVICE,
			com.cbt.ws.jooq.tables.DeviceJob.DEVICE_JOB,
			com.cbt.ws.jooq.tables.DeviceJobResult.DEVICE_JOB_RESULT,
			com.cbt.ws.jooq.tables.DeviceOs.DEVICE_OS,
			com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING,
			com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE,
			com.cbt.ws.jooq.tables.Results.RESULTS,
			com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG,
			com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE,
			com.cbt.ws.jooq.tables.TestprofileDevices.TESTPROFILE_DEVICES,
			com.cbt.ws.jooq.tables.Testrun.TESTRUN,
			com.cbt.ws.jooq.tables.Testscript.TESTSCRIPT,
			com.cbt.ws.jooq.tables.Testtarget.TESTTARGET,
			com.cbt.ws.jooq.tables.User.USER);
	}
}
