/**
 * This class is generated by jOOQ
 */
package com.cbt.ws.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in cbt
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cbt.device
	 */
	public static final com.cbt.ws.jooq.tables.Device DEVICE = com.cbt.ws.jooq.tables.Device.DEVICE;

	/**
	 * The table cbt.device_job
	 */
	public static final com.cbt.ws.jooq.tables.DeviceJob DEVICE_JOB = com.cbt.ws.jooq.tables.DeviceJob.DEVICE_JOB;

	/**
	 * The table cbt.device_job_result
	 */
	public static final com.cbt.ws.jooq.tables.DeviceJobResult DEVICE_JOB_RESULT = com.cbt.ws.jooq.tables.DeviceJobResult.DEVICE_JOB_RESULT;

	/**
	 * The table cbt.device_os
	 */
	public static final com.cbt.ws.jooq.tables.DeviceOs DEVICE_OS = com.cbt.ws.jooq.tables.DeviceOs.DEVICE_OS;

	/**
	 * The table cbt.device_sharing
	 */
	public static final com.cbt.ws.jooq.tables.DeviceSharing DEVICE_SHARING = com.cbt.ws.jooq.tables.DeviceSharing.DEVICE_SHARING;

	/**
	 * The table cbt.device_type
	 */
	public static final com.cbt.ws.jooq.tables.DeviceType DEVICE_TYPE = com.cbt.ws.jooq.tables.DeviceType.DEVICE_TYPE;

	/**
	 * The table cbt.results
	 */
	public static final com.cbt.ws.jooq.tables.Results RESULTS = com.cbt.ws.jooq.tables.Results.RESULTS;

	/**
	 * The table cbt.testconfig
	 */
	public static final com.cbt.ws.jooq.tables.Testconfig TESTCONFIG = com.cbt.ws.jooq.tables.Testconfig.TESTCONFIG;

	/**
	 * The table cbt.testprofile
	 */
	public static final com.cbt.ws.jooq.tables.Testprofile TESTPROFILE = com.cbt.ws.jooq.tables.Testprofile.TESTPROFILE;

	/**
	 * The table cbt.testprofile_devices
	 */
	public static final com.cbt.ws.jooq.tables.TestprofileDevices TESTPROFILE_DEVICES = com.cbt.ws.jooq.tables.TestprofileDevices.TESTPROFILE_DEVICES;

	/**
	 * The table cbt.testrun
	 */
	public static final com.cbt.ws.jooq.tables.Testrun TESTRUN = com.cbt.ws.jooq.tables.Testrun.TESTRUN;

	/**
	 * The table cbt.testscript
	 */
	public static final com.cbt.ws.jooq.tables.Testscript TESTSCRIPT = com.cbt.ws.jooq.tables.Testscript.TESTSCRIPT;

	/**
	 * The table cbt.testtarget
	 */
	public static final com.cbt.ws.jooq.tables.Testtarget TESTTARGET = com.cbt.ws.jooq.tables.Testtarget.TESTTARGET;

	/**
	 * The table cbt.user
	 */
	public static final com.cbt.ws.jooq.tables.User USER = com.cbt.ws.jooq.tables.User.USER;
}
